Data cleanup enhancement
sorinlab/fah-data-cleanup pull request #2
Opened 2017-10-04 06:49 UTC by xaviermartinez2012

Enhanced script by removing max run/clone arguments and using logic similar to python's `os.walk`.

2017-10-04 15:25 UTC, khaister requested changes

2017-10-04 15:25 UTC, khaister commented on fah-data-cleanup.pl
> +if (-d $projpath) {
Invert `if` to reduce nesting.

2017-10-04 15:25 UTC, khaister commented on fah-data-cleanup.pl
> +    my ($pattern, $path, @dirs, $num_dirs);
Use first line in sub body to get parameters: `my ($pattern, $path) = @_;`. This, as a result, tells you your sub's parameters.

2017-10-04 15:25 UTC, khaister commented on fah-data-cleanup.pl
> +# Arguments: pattern to search for, absolute path of directory
Please remove this comment.

2017-10-04 15:25 UTC, khaister commented on fah-data-cleanup.pl
> +    @dirs     = `ls $path | grep $pattern`;
Please use `opendir()` and `readdir()`.

2017-10-04 15:25 UTC, khaister commented on fah-data-cleanup.pl
> +        chomp $dir;
If you use `readdir()` there's no need to `chomp()`.

2017-10-04 15:25 UTC, khaister commented on fah-data-cleanup.pl
> +./fah-data-clean-up.pl <Absolute path to PROJ# directory>
Can I use relative path?

Also please use something like `<path_to_project_dir>` for style consistency in POD.

2017-10-04 16:31 UTC, khaister commented on fah-data-cleanup.pl
> +    my ($pattern, $path, @dirs, $num_dirs);
Please also rename the sub name to better show intention: this sub looks like it tries to **get dirs** that match a pattern. A language's characteristics (e.g. python's `os.walk()`) should not drive how we name things. We need to name things that's easy to understand and clearly shows meaning/intention.

2017-10-04 17:46 UTC, khaister commented on fah-data-cleanup.pl
> +    exit 1;
Please use `die` instead of `print STDOUT` + `exit 1`.

2017-11-01 16:45 UTC, khaister commented
Hi @xaviermartinez2012, any updates on this?

2017-11-01 17:38 UTC, xaviermartinez2012 commented
@khaister Lets close this pull request. The changes weren't really _that_ significant.

2018-04-30 00:56 UTC, closed without merging